apiVersion: v1
kind: Service
metadata:
  name: snmp
spec:
  externalTrafficPolicy: Local
  type: NodePort
  selector:
    app: snmp
  ports:
  - protocol: UDP
    port: 162
    targetPort: 162
    nodePort: 30162
