apiVersion: apps/v1
kind: Deployment
metadata:
  name: snmp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snmp
  template:
    metadata:
      labels:
        app: snmp
    spec:
      containers:
      - name: snmp
        image: ssenchyna/snmp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 162
        envFrom:
        - configMapRef:
            name: default-config
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi

