apiVersion: apps/v1
kind: Deployment
metadata:
  name: syslog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syslog
  template:
    metadata:
      labels:
        app: syslog
    spec:
      containers:
      - name: syslog
        image: ssenchyna/syslog:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 514
        envFrom:
        - configMapRef:
            name: default-config
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi

