network-web:
  image:
    tag: "1.0.0-97798f8"
network-api:
  image:
    tag: "1.0.0-38cf220"
configmap:
  image:
    tag: "1.0.0-feudwde"
syslog:
  image:
    tag: "1.0.0-65080fd"
snmp:
  image:
    tag: "1.0.0-a7646d6"
