network-web:
  image:
    tag: "1.0.0-69da5ba01"
network-api:
  image:
    tag: "1.0.0-4b29298"
configmap:
  image:
    tag: "1.0.0-feudwde"
syslog:
  image:
    tag: "1.0.0-996bb77"
snmp:
  image:
    tag: "1.0.0-a3897be"
