apiVersion: batch/v1
kind: CronJob
metadata:
  name: network-cron-job
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: network-cron
            image: ssenchyna/network-cron:latest
            env:
            - name: NETBOXTOKEN
              valueFrom:
                configMapKeyRef:
                  name: network-cron-config
                  key: NETBOXTOKEN
            - name: MONGOURL
              valueFrom:
                configMapKeyRef:
                  name: network-cron-config
                  key: MONGOURL
            - name: NETBOXURL
              valueFrom:
                configMapKeyRef:
                  name: network-cron-config
                  key: NETBOXURL
            - name: DISCORDURL
              valueFrom:
                configMapKeyRef:
                  name: network-cron-config
                  key: DISCORDURL
          restartPolicy: OnFailure
