kind: "Service"
apiVersion: "v1"
metadata:
  name: "netbox"
spec:
  ports:
  - name: "netbox"
    protocol: "TCP"
    port: 8000
    targetPort: 8000
    nodePort: 0

---
kind: "Endpoints"
apiVersion: "v1"
metadata:
  name: "netbox"
subsets:
- addresses:
  - ip: "10.0.5.145"
  ports:
  - port: 8000
    name: "netbox"
